apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Values.name }}-db
spec:
  capacity:
    storage: 500Mi
  storageClassName: {{ .Values.name }}-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db/{{ .Values.name }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
